version: '3.8'

services:
  web:
    build: ./react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - supabase
    networks:
      - app-network

  backend:
    build: ./rabbitmq-backend
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  supabase:
    image: supabase/postgres:15.1.0.117
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supabase
    ports:
      - "5432:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # RabbitMQ management UI
      - "5672:5672"   # RabbitMQ message broker port
    networks:
      - app-network

volumes:
  db-data:
  supabase-data:

networks:
  app-network:
    driver: bridge