version: '3.8'

services:
  web:
    build: ./react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - supabase
    networks:
      - app-network

  backend:
    build: ./rabbitmq-backend
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  supabase:
    image: supabase/postgres:15.1.0.117
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supabase
    ports:
      - "5432:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network

  validator:
    build: ./validator
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - supabase
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - app-network

volumes:
  db-data:
  supabase-data:
  grafana-data:

networks:
  app-network:
    driver: bridge