version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - db
      - supabase

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data

  supabase:
    image: supabase/postgres:15.1.0.117
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supabase
    ports:
      - "5432:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data

volumes:
  db-data:
  supabase-data: